name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js 20
      uses: actions/setup-node@v5
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm ci
    - run: npm run lint
    - name: Ensure no changes
      run: git diff --exit-code

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-15, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js 20
      uses: actions/setup-node@v5
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Playwright install
      run: npx playwright install --with-deps
    - name: Build
      run: npm run build
    - name: Run playwright-mcp tests
      run: npm test

  test_mcp_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js 20
      uses: actions/setup-node@v5
      with:
        node-version: '20'
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Playwright install
      run: npx playwright install --with-deps chromium
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
    - name: Build and push
      uses: docker/build-push-action@v7
      with:
        tags: playwright-mcp-dev:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
    - name: Run tests
      shell: bash
      run: |
        # Used for the Docker tests to share the test-results folder with the container.
        umask 0000
        npm run test -- --project=chromium-docker
      env:
        MCP_IN_DOCKER: 1
